# Generated by Django 3.0.5 on 2020-10-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('F_Name', models.CharField(max_length=20)),
                ('M_Name', models.CharField(max_length=20)),
                ('L_Name', models.CharField(max_length=20)),
                ('Phone_No', models.CharField(max_length=14)),
                ('DOB', models.DateField(max_length=8)),
                ('Street', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Pincode', models.CharField(max_length=6)),
            ],
        ),
    ]
