# Generated by Django 3.0.5 on 2020-10-10 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20201010_1633'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_hospital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='F_Name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='L_Name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='M_Name',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Patient_Records',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('P_Diagnostics', models.CharField(max_length=20)),
                ('Doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
                ('Patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
            options={
                'unique_together': {('Patient', 'Doctor')},
            },
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Of_Appointment', models.DateField(max_length=8)),
                ('Medication', models.IntegerField()),
                ('Fee_Paid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Ratings', models.IntegerField()),
                ('Patient_Records', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient_Records')),
            ],
        ),
    ]
