# Generated by Django 3.0.5 on 2020-10-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20201010_1633'),
        ('patient', '0002_auto_20201010_1633'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
        migrations.RenameModel(
            old_name='Patient_Records',
            new_name='Patient_Record',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Patient_Records',
            new_name='Patient_Record',
        ),
    ]
