# Generated by Django 3.0.5 on 2020-10-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20201010_1640'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('F_Name', 'M_Name', 'L_Name')},
        ),
    ]
