# Generated by Django 3.0.5 on 2020-10-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20201010_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_record',
            name='Name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
