# Generated by Django 3.0.5 on 2020-10-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patient_record_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Medicines',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
